
INSERT INTO PARTIDO(NOME_PARTIDO, SIGLA, IDEOLOGIA, DATA_FUNDACAO) VALUES ('Partido da Social Democracia Brasileira', 'PSDB', 'DIREITA', '1988-06-25')
INSERT INTO PARTIDO(NOME_PARTIDO, SIGLA, IDEOLOGIA, DATA_FUNDACAO) VALUES ('Partido Democrático Trabalhista', 'PDT', 'ESQUERDA', '1979-06-17')
INSERT INTO PARTIDO(NOME_PARTIDO, SIGLA, IDEOLOGIA, DATA_FUNDACAO) VALUES ('Partido dos Trabalhadores', 'PT', 'ESQUERDA', '1980-02-10')
INSERT INTO PARTIDO(NOME_PARTIDO, SIGLA, IDEOLOGIA, DATA_FUNDACAO) VALUES ('Movimento Democrático Brasileiro', 'MDB', 'CENTRO', '1980-01-15')
INSERT INTO PARTIDO(NOME_PARTIDO, SIGLA, IDEOLOGIA, DATA_FUNDACAO) VALUES ('Partido Socialista Brasileiro', 'PSB', 'ESQUERDA', '1947-08-06')

INSERT INTO ASSOCIADO(NOME, CARGO_POLITICO, DATA_NASCIMENTO, SEXO) VALUES ('FRANCISCO MORORÓ', 'PRESIDENTE', '1983-07-11', 'MASCULINO')
INSERT INTO ASSOCIADO(NOME, CARGO_POLITICO, DATA_NASCIMENTO, SEXO) VALUES ('BRUNA SONICK', 'DEPUTADO_ESTADUAL', '1990-05-30', 'FEMININO')
INSERT INTO ASSOCIADO(NOME, CARGO_POLITICO, DATA_NASCIMENTO, SEXO) VALUES ('TÂNIA MARIA', 'DEPUTADO_FEDERAL', '1962-11-17', 'FEMININO')
INSERT INTO ASSOCIADO(NOME, CARGO_POLITICO, DATA_NASCIMENTO, SEXO) VALUES ('MICHELE MORORÓ', 'VEREADOR', '1986-05-08', 'FEMININO')
INSERT INTO ASSOCIADO(NOME, CARGO_POLITICO, DATA_NASCIMENTO, SEXO) VALUES ('JOSÉ NOBERTO', 'PREFEITO', '1963-01-10', 'MASCULINO')